version: '3'
services:
  api-rest-charla:
    image: "danielmasegosa/api-rest-charla"
    ports:
     - "8081:8080"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  mongo-client:
    image: "mongoclient/mongoclient"
    ports:
      - "3000:3000"